Repository AY2425S2-CS2103T-F12-1/tp, pull requests merged in 2025-03, with the labels that each got.

#14 Add Noah Info, AboutUs Page Noah
  docs/AboutUs.md
  docs/team/noahAng.md
Labels: type.Task

#57 Add sport to existing contact and Add sports field when creating new contact
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddSportCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSportCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#73 FindSports command
  src/main/java/seedu/address/logic/commands/FindSportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindSportCommandParser.java
  src/main/java/seedu/address/model/person/SportContainsKeywordsPredicate.java
Labels: type.Story

#77 Update add command postal code
  src/main/java/seedu/address/commons/util/LocationUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/commons/util/LocationUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#76 V1.3 test findsport command and related classes
  README.md
  docs/AboutUs.md
  docs/images/somneelsaha2004.png
  src/main/java/seedu/address/logic/parser/FindSportCommandParser.java
  src/test/java/seedu/address/logic/commands/FindSportCommandTest.java
  src/test/java/seedu/address/logic/parser/FindSportCommandParserTest.java
  src/test/java/seedu/address/model/person/SportContainsKeywordsPredicateTest
Labels: type.Enhancement, type.Task

#90 Add Group field
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateGroupException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Story, type.Task

#92 Fix add group command make delete group command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, type.Task

#95 Add Ui for Group to be displayed beside list of persons
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#93 Plant uml update
  build.gradle
  docs/diagrams/ArchitectureDiagram.png
  docs/diagrams/ArchitectureSequenceDiagram.png
  docs/diagrams/BetterModelClassDiagram.png
  docs/diagrams/CommitActivityDiagram.png
  docs/diagrams/ComponentManagers.png
  docs/diagrams/DeleteSequenceDiagram.png
  docs/diagrams/LogicClassDiagram.png
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/ParserClasses.png
  docs/diagrams/StorageClassDiagram.png
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.png
  docs/diagrams/UndoRedoState0.png
  docs/diagrams/UndoRedoState1.png
  docs/diagrams/UndoRedoState2.png
  docs/diagrams/UndoRedoState3.png
  docs/diagrams/UndoRedoState4.png
  docs/diagrams/UndoRedoState5.png
  docs/diagrams/UndoSequenceDiagram-Logic.png
  docs/diagrams/UndoSequenceDiagram-Model.png
Labels: type.Task

#98 Add new AddSportSequenceDiagram png and puml file
  docs/UserGuide.md
  docs/diagrams/AddSportSequenceDiagram.png
  docs/diagrams/AddSportSequenceDiagram.puml
Labels: type.Task
